{{- if not .Values.mongodb.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kflow.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kflow.labels" . | nindent 4 }}
stringData:
  KFLOW_MONGO_URI: {{ .Values.mongodb.uri | quote }}
  KFLOW_CLICKHOUSE_DSN: {{ .Values.clickhouse.dsn | quote }}
{{- end }}
