# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runner.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crunner.proto\x12\x08kflow.v1\x1a\x1cgoogle/protobuf/struct.proto\" \n\x0fGetInputRequest\x12\r\n\x05token\x18\x01 \x01(\t\"<\n\x10GetInputResponse\x12(\n\x07payload\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"N\n\x14\x43ompleteStateRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\'\n\x06output\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x17\n\x15\x43ompleteStateResponse\"8\n\x10\x46\x61ilStateRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x13\n\x11\x46\x61ilStateResponse\"9\n\rInvokeRequest\x12(\n\x07payload\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"9\n\x0eInvokeResponse\x12\'\n\x06result\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2\xea\x01\n\rRunnerService\x12\x41\n\x08GetInput\x12\x19.kflow.v1.GetInputRequest\x1a\x1a.kflow.v1.GetInputResponse\x12P\n\rCompleteState\x12\x1e.kflow.v1.CompleteStateRequest\x1a\x1f.kflow.v1.CompleteStateResponse\x12\x44\n\tFailState\x12\x1a.kflow.v1.FailStateRequest\x1a\x1b.kflow.v1.FailStateResponse2S\n\x14ServiceRunnerService\x12;\n\x06Invoke\x12\x17.kflow.v1.InvokeRequest\x1a\x18.kflow.v1.InvokeResponseB;Z9github.com/pastorenue/kflow/internal/gen/kflow/v1;kflowv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/pastorenue/kflow/internal/gen/kflow/v1;kflowv1'
  _globals['_GETINPUTREQUEST']._serialized_start=56
  _globals['_GETINPUTREQUEST']._serialized_end=88
  _globals['_GETINPUTRESPONSE']._serialized_start=90
  _globals['_GETINPUTRESPONSE']._serialized_end=150
  _globals['_COMPLETESTATEREQUEST']._serialized_start=152
  _globals['_COMPLETESTATEREQUEST']._serialized_end=230
  _globals['_COMPLETESTATERESPONSE']._serialized_start=232
  _globals['_COMPLETESTATERESPONSE']._serialized_end=255
  _globals['_FAILSTATEREQUEST']._serialized_start=257
  _globals['_FAILSTATEREQUEST']._serialized_end=313
  _globals['_FAILSTATERESPONSE']._serialized_start=315
  _globals['_FAILSTATERESPONSE']._serialized_end=334
  _globals['_INVOKEREQUEST']._serialized_start=336
  _globals['_INVOKEREQUEST']._serialized_end=393
  _globals['_INVOKERESPONSE']._serialized_start=395
  _globals['_INVOKERESPONSE']._serialized_end=452
  _globals['_RUNNERSERVICE']._serialized_start=455
  _globals['_RUNNERSERVICE']._serialized_end=689
  _globals['_SERVICERUNNERSERVICE']._serialized_start=691
  _globals['_SERVICERUNNERSERVICE']._serialized_end=774
# @@protoc_insertion_point(module_scope)
