# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import runner_pb2 as runner__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in runner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RunnerServiceStub(object):
    """RunnerService is the internal gRPC service used by K8s Job containers
    to retrieve their input and report results back to the Control Plane.
    Exposed on :9090 (internal only, not accessible outside the cluster).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInput = channel.unary_unary(
                '/kflow.v1.RunnerService/GetInput',
                request_serializer=runner__pb2.GetInputRequest.SerializeToString,
                response_deserializer=runner__pb2.GetInputResponse.FromString,
                _registered_method=True)
        self.CompleteState = channel.unary_unary(
                '/kflow.v1.RunnerService/CompleteState',
                request_serializer=runner__pb2.CompleteStateRequest.SerializeToString,
                response_deserializer=runner__pb2.CompleteStateResponse.FromString,
                _registered_method=True)
        self.FailState = channel.unary_unary(
                '/kflow.v1.RunnerService/FailState',
                request_serializer=runner__pb2.FailStateRequest.SerializeToString,
                response_deserializer=runner__pb2.FailStateResponse.FromString,
                _registered_method=True)


class RunnerServiceServicer(object):
    """RunnerService is the internal gRPC service used by K8s Job containers
    to retrieve their input and report results back to the Control Plane.
    Exposed on :9090 (internal only, not accessible outside the cluster).
    """

    def GetInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInput': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInput,
                    request_deserializer=runner__pb2.GetInputRequest.FromString,
                    response_serializer=runner__pb2.GetInputResponse.SerializeToString,
            ),
            'CompleteState': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteState,
                    request_deserializer=runner__pb2.CompleteStateRequest.FromString,
                    response_serializer=runner__pb2.CompleteStateResponse.SerializeToString,
            ),
            'FailState': grpc.unary_unary_rpc_method_handler(
                    servicer.FailState,
                    request_deserializer=runner__pb2.FailStateRequest.FromString,
                    response_serializer=runner__pb2.FailStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kflow.v1.RunnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kflow.v1.RunnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunnerService(object):
    """RunnerService is the internal gRPC service used by K8s Job containers
    to retrieve their input and report results back to the Control Plane.
    Exposed on :9090 (internal only, not accessible outside the cluster).
    """

    @staticmethod
    def GetInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kflow.v1.RunnerService/GetInput',
            runner__pb2.GetInputRequest.SerializeToString,
            runner__pb2.GetInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kflow.v1.RunnerService/CompleteState',
            runner__pb2.CompleteStateRequest.SerializeToString,
            runner__pb2.CompleteStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kflow.v1.RunnerService/FailState',
            runner__pb2.FailStateRequest.SerializeToString,
            runner__pb2.FailStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServiceRunnerServiceStub(object):
    """ServiceRunnerService is implemented by Deployment-mode Service pods.
    The Control Plane dials the pod's ClusterIP to invoke it.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/kflow.v1.ServiceRunnerService/Invoke',
                request_serializer=runner__pb2.InvokeRequest.SerializeToString,
                response_deserializer=runner__pb2.InvokeResponse.FromString,
                _registered_method=True)


class ServiceRunnerServiceServicer(object):
    """ServiceRunnerService is implemented by Deployment-mode Service pods.
    The Control Plane dials the pod's ClusterIP to invoke it.
    """

    def Invoke(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceRunnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=runner__pb2.InvokeRequest.FromString,
                    response_serializer=runner__pb2.InvokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kflow.v1.ServiceRunnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kflow.v1.ServiceRunnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceRunnerService(object):
    """ServiceRunnerService is implemented by Deployment-mode Service pods.
    The Control Plane dials the pod's ClusterIP to invoke it.
    """

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kflow.v1.ServiceRunnerService/Invoke',
            runner__pb2.InvokeRequest.SerializeToString,
            runner__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
